### ISSUE TITLE
Wrong version documented

### ISSUE THREAD

**Issue by Yurickh** [Dayof/college_path#1]
I believe the documentation holds the wrong version of the developer's OS.
Sierra is at `10.12.4`, but the README says it is at `10.12.3`.

Using the whole version in docs forces you to either update your README every time your OS updates, which should be quite frequently, or to freeze your OS in the README's version, which is insecure.

The better solution here is to just document the major version of your OS (12), which is actually the most relevant information.

**Comment by Dayof** [comment]
Got it! Thanks for the suggestion, I'll change this on this README and others that I'll make !!
